---
-
  hosts: localhost
  vars:
    access_key: "{{ aws_access_key }}"
    secret_key: "{{ aws_secret_key }}"
  tasks:
    - name: create ec2 instance
      ec2:
        aws_access_key: "{{ access_key }}"
        aws_secret_key: "{{ secret_key }}"
        count: 1
        image: ami-08f3d892de259504d
        instance_type: t2.micro
        key_name: my-ubuntu
        region: us-east-1
        wait: true
        group_id:
                - sg-8ea365c6
                - sg-7c8d5f0f
      register: ec2

    - name: Print the ec2 public ip
      debug:
        msg: EC2 Created with IP {{  item.public_ip }}
      with_items: "{{ ec2.instances }}"
